import type {ReactNode} from 'react';
import clsx from 'clsx';
import Heading from '@theme/Heading';
import styles from './styles.module.css';

type FeatureItem = {
  title: string;
  Svg: React.ComponentType<React.ComponentProps<'svg'>>;
  description: ReactNode;
};

const FeatureList: FeatureItem[] = [
  {
    title: 'Pantry-Aware Cooking',
    Svg: require('@site/static/img/undraw_docusaurus_mountain.svg').default,
    description: (
      <>
        Start with what is already in your kitchen. The ingredient picker keeps
        staples organized by category and makes it painless to add custom items
        or leave quick notes for the chef.
      </>
    ),
  },
  {
    title: 'Nutrition-Savvy Guidance',
    Svg: require('@site/static/img/undraw_docusaurus_tree.svg').default,
    description: (
      <>
        Toggle between balanced, high-protein, low-carb, fiber-forward, or
        gluten-free focus. Each recipe comes with macros, micronutrients, and
        portion-aware cooking steps.
      </>
    ),
  },
  {
    title: 'Transparent AI Output',
    Svg: require('@site/static/img/undraw_docusaurus_react.svg').default,
    description: (
      <>
        Recipes are generated by Groq&apos;s llama-3.1-8b-instant model. Inspect the
        raw JSON payload, regenerate variations, and reset the workspace at any
        time.
      </>
    ),
  },
];

function Feature({title, Svg, description}: FeatureItem) {
  return (
    <div className={clsx('col col--4')}>
      <div className="text--center">
        <Svg className={styles.featureSvg} role="img" />
      </div>
      <div className="text--center padding-horiz--md">
        <Heading as="h3">{title}</Heading>
        <p>{description}</p>
      </div>
    </div>
  );
}

export default function HomepageFeatures(): ReactNode {
  return (
    <section className={styles.features}>
      <div className="container">
        <div className="row">
          {FeatureList.map((props, idx) => (
            <Feature key={idx} {...props} />
          ))}
        </div>
      </div>
    </section>
  );
}
